// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6oPmXnnqF2irTFV2kJv0gCEDmho81vE',
    appId: '1:291089431646:web:a5a376017f5199bf6b08cf',
    messagingSenderId: '291089431646',
    projectId: 'armuseo',
    authDomain: 'armuseo.firebaseapp.com',
    storageBucket: 'armuseo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBDMZba5YSE92llujwIXX2P1Zxs-DBqg',
    appId: '1:291089431646:android:7e7331ca44fba90e6b08cf',
    messagingSenderId: '291089431646',
    projectId: 'armuseo',
    storageBucket: 'armuseo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCjtc0uN28N-6td7MzBD5IX4l_FSfODSk',
    appId: '1:291089431646:ios:a492a436f3a8f0cd6b08cf',
    messagingSenderId: '291089431646',
    projectId: 'armuseo',
    storageBucket: 'armuseo.firebasestorage.app',
    iosBundleId: 'com.example.museoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCjtc0uN28N-6td7MzBD5IX4l_FSfODSk',
    appId: '1:291089431646:ios:a492a436f3a8f0cd6b08cf',
    messagingSenderId: '291089431646',
    projectId: 'armuseo',
    storageBucket: 'armuseo.firebasestorage.app',
    iosBundleId: 'com.example.museoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC6oPmXnnqF2irTFV2kJv0gCEDmho81vE',
    appId: '1:291089431646:web:ead875d312737f9b6b08cf',
    messagingSenderId: '291089431646',
    projectId: 'armuseo',
    authDomain: 'armuseo.firebaseapp.com',
    storageBucket: 'armuseo.firebasestorage.app',
  );

}